# Generated by Django 4.1 on 2022-09-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_customize'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('hsn', models.CharField(max_length=100)),
                ('tax_reference', models.CharField(max_length=100)),
                ('purchase_cost', models.CharField(max_length=100)),
                ('sales_cost', models.CharField(max_length=100)),
                ('tax_rate', models.CharField(max_length=100)),
            ],
        ),
    ]
