# Generated by Django 4.1 on 2022-09-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='itemtable',
        ),
    ]
