# Generated by Django 4.1 on 2022-09-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_unittable'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='account_sal',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtable',
            name='acount_pur',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtable',
            name='inter_st',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtable',
            name='intra_st',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtable',
            name='pur_desc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtable',
            name='sale_desc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
