# Generated by Django 4.1 on 2022-09-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_itemtable_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemtable',
        ),
    ]
