# Generated by Django 4.1 on 2022-09-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_delete_itemtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemtable',
            fields=[
                ('itemtableid', models.AutoField(primary_key=True, serialize=False, verbose_name='ITEMTABLEID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('hsn', models.CharField(max_length=100)),
                ('tax_reference', models.CharField(max_length=100)),
                ('purchase_cost', models.CharField(max_length=100)),
                ('sales_cost', models.CharField(max_length=100)),
                ('tax_rate', models.CharField(max_length=100)),
                ('acount_pur', models.CharField(max_length=100)),
                ('account_sal', models.CharField(max_length=100)),
                ('pur_desc', models.CharField(max_length=100)),
                ('sale_desc', models.CharField(max_length=100)),
                ('intra_st', models.CharField(max_length=100)),
                ('inter_st', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
