# Generated by Django 4.1 on 2022-09-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_itemtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='iid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.inventory'),
            preserve_default=False,
        ),
    ]
