# Generated by Django 4.1 on 2022-09-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_itemtable_iid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='itemtable',
        ),
    ]
