# Generated by Django 4.1 on 2022-09-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_itemtable_inventry_itemtable_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtable',
            name='iid',
        ),
    ]
