# Generated by Django 4.1 on 2022-09-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_itemtable_iid'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unittable',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
            preserve_default=False,
        ),
    ]
