# Generated by Django 4.1 on 2022-09-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_itemtable_cid_unittable_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='mjournal',
            fields=[
                ('mjournalid', models.AutoField(primary_key=True, serialize=False, verbose_name='MJOURNALID')),
                ('date', models.CharField(max_length=100)),
                ('ref_no', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('j_type', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('account1', models.CharField(max_length=100)),
                ('desc1', models.CharField(max_length=100)),
                ('contact1', models.CharField(max_length=100)),
                ('debit1', models.CharField(max_length=100)),
                ('credit1', models.CharField(max_length=100)),
                ('desc2', models.CharField(max_length=100)),
                ('contact2', models.CharField(max_length=100)),
                ('debit2', models.CharField(max_length=100)),
                ('credit2', models.CharField(max_length=100)),
                ('attach', models.CharField(max_length=100)),
                ('s_total', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('difference', models.CharField(max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
