# Generated by Django 4.1 on 2022-09-26 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_mjournal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mjournal',
        ),
    ]
