# Generated by Django 4.1 on 2022-09-26 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_delete_mjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='mjournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('mj_no', models.CharField(max_length=100)),
                ('ref_no', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('j_type', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('account1', models.CharField(max_length=100)),
                ('desc1', models.CharField(max_length=100)),
                ('contact1', models.CharField(max_length=100)),
                ('debit1', models.CharField(max_length=100)),
                ('credit1', models.CharField(max_length=100)),
                ('desc2', models.CharField(max_length=100)),
                ('contact2', models.CharField(max_length=100)),
                ('debit2', models.CharField(max_length=100)),
                ('credit2', models.CharField(max_length=100)),
                ('attach', models.CharField(max_length=100)),
                ('s_totaldeb', models.CharField(max_length=100)),
                ('s_totalcre', models.CharField(max_length=100)),
                ('total_deb', models.CharField(max_length=100)),
                ('total_cre', models.CharField(max_length=100)),
                ('difference', models.CharField(max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
