# Generated by Django 4.1 on 2022-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_mjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mjournal',
            name='account2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
