# Generated by Django 4.1 on 2022-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_mjournal_account2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mjournal',
            name='status',
            field=models.CharField(default='DRAFT', max_length=100),
        ),
    ]
