# Generated by Django 4.1 on 2022-09-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_mjournal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mjournal',
            name='attach',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='contact1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='contact2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='desc1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='desc2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='j_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
