# Generated by Django 4.1 on 2022-09-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_mjournal_attach_alter_mjournal_contact1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mjournal',
            name='attach',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
