# Generated by Django 4.1 on 2022-09-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_mjournal_attach'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('currencyid', models.AutoField(primary_key=True, serialize=False, verbose_name='CURRENCYID')),
                ('code', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('symbol', models.CharField(blank=True, default='', max_length=255)),
                ('decimal_places', models.CharField(blank=True, default='', max_length=255)),
                ('format', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
