# Generated by Django 4.1 on 2022-09-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_currency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='currency',
            new_name='currencies',
        ),
    ]
